### ISSUE TITLE
Plugin installation assumed to be site plugin, but contains source code, aborting installation

### ISSUE THREAD

**Issue by malpani** [elasticsearch/elasticsearch-analysis-kuromoji#54]
Trying to install this plugin against 1.4.0 gives me the following error

bin/plugin install elasticsearch/elasticsearch-analysis-kuromoji/2.4.2 (or 2.4.1)
Downloading ..............................DONE
Installed elasticsearch/elasticsearch-analysis-kuromoji/2.4.1 into /Users/malpani/Desktop/es/elasticsearch-1.4.0/plugins/analysis-kuromoji
Usage:
    -u, --url     [plugin location]   : Set exact URL to download the plugin from
    -i, --install [plugin name]       : Downloads and installs listed plugins [*]
    -t, --timeout [duration]          : Timeout setting: 30s, 1m, 1h... (infinite by default)
    -r, --remove  [plugin name]       : Removes listed plugins
    -l, --list                        : List installed plugins
    -v, --verbose                     : Prints verbose messages
    -s, --silent                      : Run in silent mode
    -h, --help                        : Prints this help message

 [*] Plugin name could be:
     elasticsearch/plugin/version for official elasticsearch plugins (download from download.elasticsearch.org)
     groupId/artifactId/version   for community plugins (download from maven central or oss sonatype)
     username/repository          for site plugins (download from github master)

Message:
   Error while installing plugin, reason: IllegalArgumentException: Plugin installation assumed to be site plugin, but contains source code, aborting installation.
6c400897a3e4:elasticsearch-1.4.0 malpani$ bin/plugin install elasticsearch/elasticsearch-analysis-kuromoji/2.4.1 -u https://github.com/elasticsearch/elasticsearch-analysis-kuromoji/archive/master.zip
-> Installing elasticsearch/elasticsearch-analysis-kuromoji/2.4.1...
Trying https://github.com/elasticsearch/elasticsearch-analysis-kuromoji/archive/master.zip...
Downloading ..............................DONE
Installed elasticsearch/elasticsearch-analysis-kuromoji/2.4.1 into /Users/malpani/Desktop/es/elasticsearch-1.4.0/plugins/analysis-kuromoji
Usage:
    -u, --url     [plugin location]   : Set exact URL to download the plugin from
    -i, --install [plugin name]       : Downloads and installs listed plugins [*]
    -t, --timeout [duration]          : Timeout setting: 30s, 1m, 1h... (infinite by default)
    -r, --remove  [plugin name]       : Removes listed plugins
    -l, --list                        : List installed plugins
    -v, --verbose                     : Prints verbose messages
    -s, --silent                      : Run in silent mode
    -h, --help                        : Prints this help message

 [*] Plugin name could be:
     elasticsearch/plugin/version for official elasticsearch plugins (download from download.elasticsearch.org)
     groupId/artifactId/version   for community plugins (download from maven central or oss sonatype)
     username/repository          for site plugins (download from github master)

Message:
   Error while installing plugin, reason: IllegalArgumentException: Plugin installation assumed to be site plugin, but contains source code, aborting installation.

**Comment by malpani** [comment]
Having said that the artifact way for install works
<pre>
plugin --install analysis-kuromoji \
       --url file:target/releases/elasticsearch-analysis-kuromoji-X.X.X-SNAPSHOT.zip
</pre>

**Comment by johtani** [comment]
Hi @malpani 
I tried to run your command "bin/plugin install elasticsearch/elasticsearch-analysis-kuromoji/2.4.2" against elasticsearch 1.4.0.
Then it works for me.

How is the situation afterward?

**Comment by malpani** [comment]
@johtani - Not sure why it didnt work for me. Trying against 1.4.2 also didn't work for me. But was able to get the locallly built artifact to install. You can close this if it does not affect anyone else.

**Comment by johtani** [comment]
@malpani OK. I close this.
If your network require to pass the proxy, see the following link.

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-plugins.html#_proxy_settings
